Updated GitHub Actions workflow to fix formatting issues

diff --git a/.github/workflows/action-terraform-verify.yml b/.github/workflows/action-terraform-verify.yml
--- a/.github/workflows/action-terraform-verify.yml
+++ b/.github/workflows/action-terraform-verify.yml
@@ -15,7 +15,7 @@ permissions:
   contents: read
 
 jobs:
-  validate:
+  terraform-format:
     runs-on: ubuntu-latest
     name: Terraform Format Check
     steps:
@@ -38,15 +38,20 @@ jobs:
       - name: Validate Terraform Formatting (fmt)
         run: |
           set +e
+          CHECK_STATUS=0
           for changed_file in ${{ steps.pr_files.outputs.added_modified }}; do
             if [[ $changed_file == *.tf ]]; then
-              terraform fmt -check $changed_file
-              if [[ $? -ne 0 ]]; then
-                echo "❌ terraform fmt failed - ${changed_file}" >> $GITHUB_STEP_SUMMARY
-                exit 1
-              fi
+              terraform fmt -check $changed_file || CHECK_STATUS=1
             fi
           done
+          echo "CHECK_STATUS=$CHECK_STATUS" >> $GITHUB_ENV
+
+      - name: Fail if Formatting Issues Found
+        run: |
+          if [[ "$CHECK_STATUS" -ne 0 ]]; then
+            echo "❌ Terraform formatting failed!"
+            exit 1
+          fi
 
   terraform-validate:
     runs-on: ubuntu-latest
